# Load project's shell environment variables
import os
import sys
from dotenv import load_dotenv
load_dotenv(dotenv_path="../project.env")
sys.path.append(os.environ["PYTHONPATH"])

# Load project-wide variables
import superheader as sup

###############################################################################
################################## Filesystem #################################

import os

# Directory where the raw videos live
RAW_DATA_ROOT = os.path.join(sup.DATA_ROOT, 'raw', sup.NUM_CLASSES)

if os.path.exists(RAW_DATA_ROOT)==False:
  raise Exception(f"Directory {RAW_DATA_ROOT} does not exist. Please investigate") 
else:
  print(f"Directory {RAW_DATA_ROOT} exists. Continuing with execution")

# Directory where the data generated by PH1 will live
PH1_DATA_ROOT = os.path.join(sup.DATA_ROOT, 'PH1', sup.NUM_CLASSES)
PH1_DATA_PERFRAME_CSV = os.path.join(PH1_DATA_ROOT, 'perframe.csv')
PH1_DATA_ACTIVE_CSV = os.path.join(PH1_DATA_ROOT, 'active.csv')
PH1_DATA_PERVIDEO_CSV = os.path.join(PH1_DATA_ROOT, 'pervideo.csv')

if os.path.exists(PH1_DATA_ROOT)==False:
  print(f"Directory {PH1_DATA_ROOT} does not exist. Creating it and continuing with execution")
  os.makedirs(PH1_DATA_ROOT)
else:
  print(f"Directory {PH1_DATA_ROOT} exists. Continuing with execution")

################################## Filesystem #################################
###############################################################################
####################### nltk corpus to pandas dataframe #######################

from file_reading.fs2df import get_tags as get_tags

####################### nltk corpus to pandas dataframe #######################
###############################################################################
############################## Feature extraction #############################
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # # # # # # # # # # # # Step 1: Video to landmarks  # # # # # # # # # # # # #

import feature_extraction.ph1step1 as step1

# # # # # # # # # # # # # Step 1: Video to landmarks  # # # # # # # # # # # # #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #