# Load project's shell environment variables
import os
import sys
from dotenv import load_dotenv
load_dotenv(dotenv_path="../project.env")
sys.path.append(os.environ["PYTHONPATH"])

# Load project-wide variables
import superheader as sup

###############################################################################
################################## Filesystem #################################

import os

# Directory where the extracted data from PH1 lives
PH1_DATA_ROOT = os.path.join(sup.DATA_ROOT, 'PH1', sup.NUM_CLASSES)
PH1_DATA_PERFRAME_CSV = os.path.join(PH1_DATA_ROOT, 'perframe.csv')
PH1_DATA_ACTIVE_CSV = os.path.join(PH1_DATA_ROOT, 'active.csv')
PH1_DATA_PERVIDEO_CSV = os.path.join(PH1_DATA_ROOT, 'pervideo.csv')

if os.path.exists(PH1_DATA_ROOT)==False:
  raise Exception(f"Directory {PH1_DATA_ROOT} does not exist. Please investigate") 
else:
  print(f"Directory {PH1_DATA_ROOT} exists. Continuing with execution")

# Directory where the data generated by PH2 will live
PH2_DATA_ROOT = os.path.join(sup.DATA_ROOT, 'PH2', sup.NUM_CLASSES)

if os.path.exists(PH2_DATA_ROOT)==False:
  print(f"Directory {PH2_DATA_ROOT} does not exist. Creating it and continuing with execution")
  os.makedirs(PH2_DATA_ROOT)
else:
  print(f"Directory {PH2_DATA_ROOT} exists. Continuing with execution")

################################## Filesystem #################################
###############################################################################